---
- name: check if opencv is already installed in install_prefix
  stat:
    path: "{{ install_prefix }}/lib/libopencv_core.so"
  register: st

- name: set opencv_installed fact
  set_fact:
    opencv_installed: "{{ st.stat.isreg is defined and st.stat.islnk }}"

- block:
  - include: "{{ ansible_distribution | lower }}.yml"
  - include: "compile.yml"
  - include: "install.yml"
  when: reinstall or not opencv_installed

